### ISSUE TITLE
Complete Achievement and AchievementCategory Key on the GOOD format

### ISSUE THREAD

**Issue by LudovicMalot** [dval-in/dvalin-data#21]

**Comment by SakshamGairola** [comment]
Writing a py script to read from `data/EN/AchievementCategory/..` and ingest into `AchievementCategoryKey.ts` and `AchievementKey.ts`
Are we sure that there are no elusive achievemnts in there i.e., `Hanging Gardens of Plucked Jade`?
Also tiered achievemnts like `Zoo Tycoon` will be ingested as a Single entry into types.
@LudovicMalot  @maalni  @Mulugruntz

**Comment by maalni** [comment]
You could append numbers behind tiered achievements (i.e. ZooTycoon1, ZooTycoon2 & ZooTycoon3)
