### ISSUE TITLE
Add event data

### ISSUE THREAD

**Issue by LudovicMalot** [dval-in/dvalin-data#28]
Create and fill a JSON with all data following the event types

**Comment by Mulugruntz** [comment]
What kind of data would we like for this?

As I see it, there are at least 3 different source models.
- honey impact https://genshin.honeyhunterworld.com/events/?lang=EN
  - They have lots of details (probably too much, unneeded), and miss basic ones, such as the images
- wiki https://genshin-impact.fandom.com/wiki/Event/History
  - can be a bit more tricky to scrap, as it's more free-form
  - All info is there
- hoyolab https://www.hoyolab.com/home/events
  - There's actually an API: https://bbs-api-os.hoyolab.com/community/community_contribution/wapi/event/list?gids=2&offset=0&size=15 (the size seems ignored)

---

Unrelated:

Regarding the Hoyo API, as it's accessible with no authentication (public), it "should" be fine.
I noticed that for all characters as well there's an API. 
- Example with Chevreuse: `GET` https://sg-wiki-api-static.hoyolab.com/hoyowiki/genshin/wapi/entry_page?entry_page_id=4577
- the `entry_page_id` can be found there: `POST` https://sg-wiki-api.hoyolab.com/hoyowiki/genshin/wapi/get_entry_page_list
```shell
curl 'https://sg-wiki-api.hoyolab.com/hoyowiki/genshin/wapi/get_entry_page_list' \
  -H 'Referer: https://wiki.hoyolab.com/' \
  --data-raw '{"filters":[],"menu_id":"2","page_num":1,"page_size":30,"use_es":true}' \
  --compressed
```

**Comment by Mulugruntz** [comment]
There's also the type of events that we want to collect.
Only the ones that actually appear in-game?
- List Human: https://www.hoyolab.com/circles/2/27/official?page_type=27&page_sort=news
- List API: https://bbs-api-os.hoyolab.com/community/post/wapi/getNewsList?gids=2&last_id=2&page_size=1&type=3
- Single Human: https://www.hoyolab.com/article/24683839
- Single API: https://bbs-api-os.hoyolab.com/community/post/wapi/getPostFull?post_id=24596241&read=1&scene=1
All the community events?
How about the web events?

Is the goal to create a timeline ( https://paimon.moe/timeline )?

In this case, we can get a very limited subset of events (they usually reuse keywords).

**Comment by LudovicMalot** [comment]
> All the community events? How about the web events?
> 
> Is the goal to create a timeline ( https://paimon.moe/timeline )?
> 
> In this case, we can get a minimal subset of events (they usually reuse keywords).
As we are the data team I would suggest we save the most data possible but with proper classification for web events, in-game events etc...
I think the Hoyolab API should be fine for all types of events. No need to scrap Honey or the Wiki. Especially with the language issue.

To have the history of the event, we probably will need to parse (or manually) the wiki. It's possible that some GitHub repos already store those in a friendlier format. But this is not important and seems like a lot of work for not necessarily a significant impact. If it's too time-consuming, better to raise an issue with ultra-low priority for this task.

**Comment by Mulugruntz** [comment]
To be noted that I cannot assign myself, I don't have the permissions.

**Comment by LudovicMalot** [comment]
> To be noted that I cannot assign myself, I don't have the permissions

should be fixed

**Comment by Mulugruntz** [comment]
Still nope :)
