### ISSUE TITLE
redeemable code scraper

### ISSUE THREAD

**Issue by teehee567** [dval-in/dvalin-data#29]
problem- how to give codes to users

solutions- manually upload them, scrape them, since theres no open api

i propose we scrape them, a scraper wouldnt be that hard just taking information from a few websites i already have an example for this https://github.com/GauravM512/genshin-redeem-code just need to update and write up. since this will be an hourly sort of scrape since you want to have the codes fast, im proposing i upload the code here but run it on a raspberry pi and have it upload to a file in dvalin data as a github action

**Comment by LudovicMalot** [comment]
Feel free to do it
