### ISSUE TITLE
Typescript types look incorrect

### ISSUE THREAD

**Issue by Mulugruntz** [dval-in/dvalin-data#33]
About the docstring `@TJS-required`, such as in
```typescript
export type TalentMaterial = {
	/**
	 * @TJS-required
	 */
	level: number;
	cost: number;
	items: AscensionMaterial[];
};
```

Isn't it applied only on `level`, in the above case?

In their examples https://github.com/YousefED/typescript-json-schema/blob/master/api.md the docstring is applied to what comes next.

Likewise, for this:

```typescript
tcgCharacterCard: undefined | string; // Id
```

generates the following type:
```json
    "tcgCharacterCard": {
      "type": "string"
    },
...

  "required": [
...
    "tcgCharacterCard",
...
  ],
```

I'm not sure why there would be `undefined` if it ends up being required.

Likewise, we already have several json data files that don't match their schemas.
Example with `schemas/TCGMonsterCard.json` and `data/DE/TCGMonsterCard/AnemoSamachurl.json`, because it has `null` value for title (not only).
So, in `types/TCGMonsterCard.ts`: 
```typescript
title?: string;
```
in the schema:
```json
    "title": {
      "type": "string"
    }
  },
  "required": [
    "attributes",
    "id",
    "name",
    "skills"
  ],
```
And in the data:
```json
  "title": null,
```

For nullable types, it seems that the way to go is this:
```typescript
	/** @nullable */
	title?: string;
```

Source: https://github.com/YousefED/typescript-json-schema/blob/master/api.md#type-nullable

**Comment by LudovicMalot** [comment]
> I'm not sure why there would be undefined if it ends up being required.
The field is required (helps for strict validation) but the data can be undefined if there is no data yet. It will also simplify slightly the devs part as they won't have to check if the field exist but rather just check if the value is not falsy.
The rest I 100% agree we have a lot of mismatch, error and a lot of improvement can be made.

**Comment by Mulugruntz** [comment]
The thing is, `undefined` is not a valid JSON value. 
A valid one would be `null`, but to make it nullable, we need `/** @nullable */.
`
